services:
  ###> symfony/application ###
  app:
    ports:
      - "9000:9000"
    restart: always
  messenger-worker:
    restart: always

  ###< symfony/application ###

  ###> symfony/nginx ###
  nginx:
    ports:
      - "8000:80"
    restart: always
  ###< symfony/nginx ###

  ###> symfony/doctrine ###
  database:
    ports:
      - "5432:5432"
    restart: always
  ###< symfony/doctrine ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: always
  ###< symfony/mailer ###

  ###> adminer ###
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always
###< adminer ###

